### ISSUE TITLE
As a user, I can take a sentiment quiz

### ISSUE THREAD

**Issue by anthony-iacono** [jphorner/wellnews#6]
- [x] Add sentiment form w/ emojis and submit button
- [x] Route to home page on submit
- [x] Get articles from NYT
- [x] Isolate and clean relevant data

Acceptance Criteria
- Scenario: As a user, I'm feeling negative/neutral/positive and want to read the news
- Given: A sentiment quiz
- When I select my sentiment and click the submit button
- Then I'm taken to the feed and see the top articles

**Comment by anthony-iacono** [comment]
@najinl Would you mind if I re-opened this issue? We've only really completed the first of its four tasks.

**Comment by najinl** [comment]
@anthony-iacono I don't mind, go for it!
